language: python
python:
  - 3.6
install:
  - pip install -r requirements.txt
script:
  - python manage.py test

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-east-2"  
  app: "hacktomorrow.org"
  env: $ELASTIC_BEANSTALK_ENV
  bucket_name: $S3_BUCKET_NAME

notifications:
  email:
    - armaangupta01@gmail.com
    - hacktomorrow.root@gmail.com
  on_success: always
  on_failure: always