language: python
python: 
  - 3.6
install:
  - pip install -r requirements.txt
script:
  - python tests.py

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  skip_cleanup: true
  region: "us-east-2"  
  app: "hacktomorrow.tcff.co"
  env: $ELASTIC_BEANSTALK_ENV
  bucket_name: $S3_BUCKET_NAME

notifications:
  slack: thecreativefoundation:n3PZ4D7QrW3uXjH7QdBH5exQ
  on_failure: always
  on_success: always